services:
  strapi:
    container_name: strapi
    build:
      context: ./strapi
      dockerfile: Dockerfile
    # restart: unless-stopped
    env_file: ./strapi/.env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    # volumes:
    # - ../strapi/config:/opt/app/config
    # - ../strapi/src:/opt/app/src
    # - ../strapi/public/uploads:/opt/app/public/uploads
    ports:
      - '${CMS_PORT:-1337}:1337'
    networks:
      - default

networks:
  default:
    name: 48-network
    driver: bridge
